@startmindmap javascript
title JavaScript 结构

* JavaScript
** 运行时
*** 数据结构
**** 类型
***** 7 种语言类型
***** 7 种规范类型
**** 实例（内置对象）
*** 执行过程
**** 事件循环
**** 微任务执行
**** 函数执行
**** 语句执行
** 文法
*** 词法
*** 语法
** 语义

@endmindmap